### ISSUE TITLE
adjust to new arche version

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/odeeg#6]

**Comment by csae8092** [comment]
done, detail views works, list view thumbs work (in theory but not in practise as the current implementation is too slow); anyway since the needed functionality get thumbs for child resources of collection x) might be useful in other projects, maybe this could be tackled on e.g. dissemination service level...)

**Comment by zozlak** [comment]
> list view thumbs work (in theory but not in practise as the current implementation is too slow); anyway since the needed functionality get thumbs for child resources of collection x) might be useful in other projects, maybe this could be tackled on e.g. dissemination service level...

Could you elaborate a little more on that? So I understand what it's about and how to see it  (and the performance issue) in action. Without that it will be difficult to come up with a solution :)

**Comment by csae8092** [comment]
good point made by @zozlak `start using acdh:isTitleImageOf`
